dist: xenial
language: bash
services:
  - docker
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

jobs:
  include:
    - stage: codestyle
      # Check Codestyle using go fmt
      services: []
      language: go
      if: type = pull_request
      go:
        - 1.12.x
      # skip install
      install: true
      script:
        - echo "Checking code style..."
        - unformatted=$(gofmt -l .)
        - |
          if [ ! -z "$unformatted" ]; then
            echo "Code Style Check failed for the following files: ${unformatted}".
            echo "Please run: gofmt -w ."
            echo "After that ammend your commit (e.g.: git add ${unformatted} && git commit --amend --no-edit) and force push the changes (git push -f)."
            travis_terminate 1
          fi

    - stage: tests
      # Run tests
      services: []
      language: go
      if: type = pull_request
      go:
        - 1.12.x
      # cache some go files
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
      script:
        - go build ./...
        - go test -race -v ./...
