---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: generic-executor-service
  labels:
    "app": "keptn"
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: generic-executor-service-secrets
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: generic-executor-service-secrets
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generic-executor-service-secrets
subjects:
  - kind: ServiceAccount
    name: generic-executor-service

---
# Deployment of our generic-executor-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-executor-service
spec:
  selector:
    matchLabels:
      run: generic-executor-service
  replicas: 1
  template:
    metadata:
      labels:
        run: generic-executor-service
    spec:
      serviceAccountName: generic-exectuor-service
      containers:
        - name: generic-executor-service
          image: grabnerandi/generic-executor-service:0.2
          ports:
            - containerPort: 8080
          env:
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace                
            - name: YOURCUSTOMENV
              value: YOURCUSTOMVALUE
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_API_TOKEN
            - name: DT_TENANT
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_TENANT
            - name: KEPTN_API_URL
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_API_URL
            - name: KEPTN_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_API_TOKEN
            - name: KEPTN_BRIDGE_URL
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_BRIDGE_URL
                  optional: true
        - name: distributor
          image: keptn/distributor:0.7.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: 'generic-executor-service'
        
---
# Expose generic-executor-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: generic-executor-service
  labels:
    run: generic-executor-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: generic-executor-service